### ISSUE TITLE
Creating bucket on GCP and labelling them as per ID.gif on the bucket

### ISSUE THREAD

**Issue by isamia-can-code** [JuanS286/gif_auto_audio_description#16]

**Comment by Lmosoriob** [comment]
I proceed successfully with the bucket Creation for GIF Storage in GCP named gif-bucket-1000 to store 1000 processed GIFs.
The bucket follows the required structure:
/dataset/gifs/ contains GIF files renamed with their unique IDs.
/dataset/train.txt, /dataset/val.txt, and /dataset/test.txt are created for organizing GIFs into training, validation, and testing datasets.
This bucket is already for storing and retrieving the processed GIF data for future model training and validation tasks.
