### ISSUE TITLE
M1 - Preprocessing/Dashboard - get Frame count

### ISSUE THREAD

**Issue by isamia-can-code** [JuanS286/gif_auto_audio_description#21]
This task is to extract the frame count for all the GIFs in the dataset so that we have the minimum and maximum count. Secondly, it will also help to add the frame count on the dashboard.

**Comment by isamia-can-code** [comment]
First step was to create multiple small files with the frame counts (due to long processing times and computational power limitations). 

 [updated_csv_90000.zip](https://github.com/user-attachments/files/17358065/updated_csv_90000.zip)

**Comment by isamia-can-code** [comment]
Second step was to 
- combine the small files
- sort the df by ID 
- address any 'unreachable statuses' 
- find frame count for 'unreachable statuses' alternatively 
- dump the dataframe into a new tsv file called "all_frame_count.tsv"

File can be found at: https://github.com/JuanS286/gif_auto_audio_description/blob/dev/Preprocessing/kheshini/all_frame_counts.tsv

**Comment by isamia-can-code** [comment]
@JuanSCampos , @anateran0501 kindly advise if more is needed on the frames processing. :)

**Comment by JuanSCampos** [comment]
The frame count was added and displayed on the final version dashboard.
