### ISSUE TITLE
M5 - Audio Creation with GCP

### ISSUE THREAD

**Issue by isamia-can-code** [JuanS286/gif_auto_audio_description#42]
This task aims to merge the UI with audio creation using GCP. Basically, if multiple GIF links are uploaded, they are to be converted to audio. This task will 
a. create the audio for a single GIF link 
b. create audio for multiple GIF links using the models.

**Comment by isamia-can-code** [comment]
The integration of UI to multiple GIF links processing was done. The UI can process multiple links and turn them into audios.

**Comment by isamia-can-code** [comment]
![Image](https://github.com/user-attachments/assets/e090dcaf-d6d0-4d08-9c84-57fba0efb621)

**Comment by isamia-can-code** [comment]
@JuanSCampos @anateran0501 kindly review! thanks :)

**Comment by anateran0501** [comment]
Image of Demo.
Noted.

**Comment by JuanSCampos** [comment]
The UI now successfully converts multiple GIF links into audio descriptions, delivering the intended functionality. Closing this issue
